=== sarv1208/sistema-bar/docs/cocktail-04.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://barassistant.app/cocktail-04.schema.json",
    "title": "Cocktail recipe - Draft 04",
    "description": "Schema for a cocktail recipe.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "name": {
            "description": "Name of the recipe",
            "type": "string",
            "minLength": 1,
            "examples": ["Margarita"]
        },
        "instructions": {
            "description": "Recipe instructions",
            "type": "string",
            "minLength": 1,
            "examples": [
                "Shake all ingredients with ice and strain into a chilled glass."
            ]
        },
        "created_at": {
            "description": "Date of recipe",
            "type": ["string", "null"],
            "format": "date-time",
            "examples": ["2024-07-21T15:30:00Z"]
        },
        "source": {
            "description": "Source of the recipe, either URL, author or book reference",
            "type": ["string", "null"],
            "minLength": 1,
            "examples": ["https://example.com/margarita-recipe", "John Doe", "Death&Co"]
        },
        "description": {
            "description": "Recipe description",
            "type": ["string", "null"],
            "minLength": 1,
            "examples": [
                "A refreshing blend of tequila, lime juice, and triple sec."
            ]
        },
        "garnish": {
            "description": "Cocktail garnish",
            "type": ["string", "null"],
            "minLength": 1,
            "examples": ["Lime wheel"]
        },
        "abv": {
            "description": "Total ABV of made cocktail",
            "type": ["number", "null"],
            "minimum": 0,
            "maximum": 100,
            "examples": [12.5]
        },
        "tags": {
            "description": "Short keywords to describe cocktail",
            "type": "array",
            "minItems": 0,
            "uniqueItems": true,
            "items": {
                "type": "string",
                "minLength": 1
            },
            "examples": [["refreshing", "citrus", "classic"]]
        },
        "glass": {
            "description": "Glassware type, like 'Coupe', 'Highball', etc.",
            "type": ["string", "null"],
            "minLength": 1,
            "examples": ["Coupe"]
        },
        "method": {
            "description": "Cocktail method",
            "type": ["string", "null"],
            "minLength": 1,
            "examples": ["Shake"]
        },
        "images": {
            "description": "List of cocktail images",
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "title": "Image",
                "additionalProperties": false,
                "properties": {
                    "uri": {
                        "type": "string",
                        "anyOf": [
                            {
                                "format": "uri"
                            },
                            {
                                "description": "Absolute or relative local file path",
                                "pattern": "^(/|\\./|\\.\\./).+"
                            }
                        ],
                        "examples": [
                            "https://example.com/image.jpg",
                            "/path/to/image.png"
                        ]
                    },
                    "placeholder_hash": {
                        "description": "Computed placeholder hash, like thumbhash, blurhash and similar",
                        "type": ["string", "null"]
                    },
                    "copyright": {
                        "description": "Image copyright information",
                        "type": "string",
                        "examples": ["© 2024 Bar Assistant"]
                    }
                },
                "required": ["uri", "copyright"]
            }
        },
        "ingredients": {
            "description": "List of cocktail ingredients and substitutes (can be empty)",
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "title": "Cocktail ingredient",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "description": "Name of the ingredient",
                        "type": "string",
                        "minLength": 1,
                        "examples": ["Tequila"]
                    },
                    "amount": {
                        "description": "Amount of the ingredient",
                        "type": "number",
                        "minimum": 0,
                        "maximum": 99999,
                        "examples": [50]
                    },
                    "units": {
                        "description": "Units for the amount",
                        "type": "string",
                        "minLength": 1,
                        "examples": ["ml"]
                    },
                    "optional": {
                        "description": "Indicates if the ingredient is optional",
                        "type": "boolean",
                        "examples": [false]
                    },
                    "amount_max": {
                        "description": "Maximum amount of the ingredient",
                        "type": ["number", "null"],
                        "minimum": 0,
                        "maximum": 99999,
                        "examples": [60]
                    },
                    "note": {
                        "description": "Additional note related to the cocktail ingredient",
                        "type": ["string", "null"],
                        "examples": ["Preferably blanco"]
                    },
                    "substitutes": {
                        "type": "array",
                        "minItems": 0,
                        "items": {
                            "type": "object",
                            "title": "Cocktail ingredient substitute",
                            "additionalProperties": false,
                            "properties": {
                                "name": {
                                    "description": "Name of the substitute ingredient",
                                    "type": "string",
                                    "minLength": 1,
                                    "examples": ["Mezcal"]
                                },
                                "amount": {
                                    "description": "Amount of the substitute ingredient",
                                    "type": ["number", "null"],
                                    "examples": [50]
                                },
                                "units": {
                                    "description": "Units for the amount",
                                    "type": ["string", "null"],
                                    "examples": ["ml"]
                                },
                                "amount_max": {
                                    "description": "Maximum amount of the substitute ingredient",
                                    "type": ["number", "null"],
                                    "examples": [60]
                                }
                            },
                            "required": ["name"]
                        }
                    }
                },
                "required": ["name", "amount", "units"]
            }
        }
    },
    "required": ["name", "instructions"]
}

=== sarv1208/sistema-bar/tests/fixtures/external/recipe.json
{
    "name": "Gin and Tonic",
    "instructions": "Cocktail instructions go here",
    "created_at": "2020-01-01T12:00:00+00:00",
    "description": "Cocktail description goes here",
    "source": "https://barassistant.app",
    "garnish": "Straw and lemon wheel",
    "abv": 32.3,
    "tags": [],
    "glass": "Highball",
    "method": "Shake",
    "images": [
        {
            "uri": "http://localhost/uploads/tests/non_existing_image.jpg",
            "placeholder_hash": null,
            "copyright": "Exported copyright"
        }
    ],
    "ingredients": [
        {
            "name": "Gin",
            "amount": 45,
            "units": "ml",
            "optional": false,
            "amount_max": 60,
            "note": "Ingredient note",
            "substitutes": []
        }
    ]
}
